const _menuShapeNow = {
  id: 'documentation',
  title: 'Get Started',
  navTitle: 'Docs',
  href: '/docs/quick-start/',
  items: [
    {
      kind: 'page',
      id: 'quickStart',
      title: 'Quick Start',
      navTitle: 'Quick Start',
      href: '/docs/quick-start/',
    },
    {
      kind: 'page',
      id: 'concepts',
      title: 'Concepts',
      navTitle: 'Concepts',
      href: '/docs/concepts/',
    },
    {
      kind: 'page',
      id: 'bestPractices',
      title: 'Best Practices',
      navTitle: 'Best Practices',
      href: '/docs/best-practices/',
    },
    {
      kind: 'divider',
      id: 'guides-divider',
      title: 'Guides',
    },
    {
      kind: 'group',
      id: 'server-guides',
      title: 'Server Integration',
      collapsible: {
        isDefaultOpen: false,
      },
      items: [
        {
          kind: 'page',
          id: 'serverIntegration',
          title: 'Server Integration',
          navTitle: 'Server Integration',
          href: '/docs/server-integration/',
        },
        {
          kind: 'page',
          id: 'next',
          title: 'Next.js',
          navTitle: 'Next.js',
          href: '/docs/next/',
        },
        {
          kind: 'page',
          id: 'svelteKit',
          title: 'SvelteKit',
          navTitle: 'SvelteKit',
          href: '/docs/svelte-kit/',
        },
        {
          kind: 'page',
          id: 'vike',
          title: 'Vike',
          navTitle: 'Vike',
          href: '/docs/vike/',
        },
        {
          kind: 'page',
          id: 'nuxt',
          title: 'Nuxt',
          navTitle: 'Nuxt',
          href: '/docs/nuxt/',
        },
        {
          kind: 'page',
          id: 'reactRouter',
          title: 'React Router',
          navTitle: 'React Router',
          href: '/docs/react-router/',
        },
        {
          kind: 'page',
          id: 'reactNative',
          title: 'React Native',
          navTitle: 'React Native',
          href: '/docs/react-native/',
        },
        {
          kind: 'page',
          id: 'bundler',
          title: 'Bundlers',
          navTitle: 'Bundlers',
          href: '/docs/bundler/',
        },
      ],
    },
    {
      kind: 'page',
      id: 'initialData',
      title: 'Initial Data',
      navTitle: 'Initial Data',
      href: '/docs/initial-data/',
    },
    {
      kind: 'page',
      id: 'permissions',
      title: 'Permissions',
      navTitle: 'Permissions',
      href: '/docs/permissions/',
    },
    {
      kind: 'page',
      id: 'validation',
      title: 'Validation',
      navTitle: 'Validation',
      href: '/docs/validation/',
    },
    {
      kind: 'page',
      id: 'fileUploads',
      title: 'File Uploads',
      navTitle: 'File Uploads',
      href: '/docs/file-uploads/',
    },
    {
      kind: 'page',
      id: 'errorHandling',
      title: 'Error Handling',
      navTitle: 'Error Handling',
      href: '/docs/error-handling/',
    },
    {
      kind: 'divider',
      id: 'learn-more-divider',
      title: 'Learn More',
    },
    {
      kind: 'page',
      id: 'whySchemaless',
      title: 'Why Schemaless?',
      navTitle: 'Why Schemaless?',
      href: '/docs/why-schemaless/',
    },
    {
      kind: 'page',
      id: 'howItWorks',
      title: 'How It Works',
      navTitle: 'How It Works',
      href: '/docs/how-it-works/',
    },
  ],
}

const _menuShapeNew = {
  id: 'documentation',
  title: 'Docs',
  navTitle: 'Docs',
  href: '/docs/quick-start/', // can be optional
  items: [
    {
      kind: 'group',
      id: 'getting-started',
      title: 'Getting Started',
      items: [
        {
          kind: 'page',
          id: 'quickStart',
          title: 'Quick Start',
          navTitle: 'Quick Start',
          href: '/docs/quick-start/',
        },
        {
          kind: 'page',
          id: 'concepts',
          title: 'Concepts',
          navTitle: 'Concepts',
          href: '/docs/concepts/',
        },
        {
          kind: 'page',
          id: 'bestPractices',
          title: 'Best Practices',
          navTitle: 'Best Practices',
          href: '/docs/best-practices/',
        },
      ],
    },
    {
      kind: 'group',
      id: 'guides',
      title: 'Guides', // can be optional - if not there the divider should not show
      items: [
        {
          kind: 'group',
          id: 'server-guides',
          title: 'Server Integration',
          href: '/docs/server-integration/', // can be optional
          collapsible: {
            isDefaultOpen: false,
          },
          items: [
            {
              kind: 'page',
              id: 'next',
              title: 'Next.js',
              navTitle: 'Next.js',
              href: '/docs/next/',
            },
            {
              kind: 'page',
              id: 'svelteKit',
              title: 'SvelteKit',
              navTitle: 'SvelteKit',
              href: '/docs/svelte-kit/',
            },
            {
              kind: 'page',
              id: 'vike',
              title: 'Vike',
              navTitle: 'Vike',
              href: '/docs/vike/',
            },
            {
              kind: 'page',
              id: 'nuxt',
              title: 'Nuxt',
              navTitle: 'Nuxt',
              href: '/docs/nuxt/',
            },
            {
              kind: 'page',
              id: 'reactRouter',
              title: 'React Router',
              navTitle: 'React Router',
              href: '/docs/react-router/',
            },
            {
              kind: 'page',
              id: 'reactNative',
              title: 'React Native',
              navTitle: 'React Native',
              href: '/docs/react-native/',
            },
            {
              kind: 'page',
              id: 'bundler',
              title: 'Bundlers',
              navTitle: 'Bundlers',
              href: '/docs/bundler/',
            },
          ],
        },
        {
          kind: 'page',
          id: 'initialData',
          title: 'Initial Data',
          navTitle: 'Initial Data',
          href: '/docs/initial-data/',
        },
        {
          kind: 'page',
          id: 'permissions',
          title: 'Permissions',
          navTitle: 'Permissions',
          href: '/docs/permissions/',
        },
        {
          kind: 'page',
          id: 'validation',
          title: 'Validation',
          navTitle: 'Validation',
          href: '/docs/validation/',
        },
        {
          kind: 'page',
          id: 'fileUploads',
          title: 'File Uploads',
          navTitle: 'File Uploads',
          href: '/docs/file-uploads/',
        },
        {
          kind: 'page',
          id: 'errorHandling',
          title: 'Error Handling',
          navTitle: 'Error Handling',
          href: '/docs/error-handling/',
        },
      ],
    },
    {
      kind: 'group',
      id: 'learn-more',
      title: 'Learn More',
      items: [
        {
          kind: 'page',
          id: 'whySchemaless',
          title: 'Why Schemaless?',
          navTitle: 'Why Schemaless?',
          href: '/docs/why-schemaless/',
        },
        {
          kind: 'page',
          id: 'howItWorks',
          title: 'How It Works',
          navTitle: 'How It Works',
          href: '/docs/how-it-works/',
        },
      ],
    },
  ],
}
