export const Heading = {
  scaffoldNewVikeApp: 'Scaffold new Vike app',
  addSsrSsgToVite: 'Add SSR/SSG to existing Vite app',
  whyVike: 'Why Vike',
  faq: 'FAQ',
  openSourcePricing: 'Open Source Pricing',
  freeProgram: 'Free Program',
  extensions: 'Extensions',
  team: 'Team',
  dataFetching: 'Data Fetching',
  preRendering: 'Pre-rendering (SSG)',
  ssrVsSpa: 'SSR vs SPA',
  headTags: '`<head>` tags',
  commonIssues: 'Common Issues',
  routing: 'Routing',
  baseUrl: 'Base URL',
  activeLinks: 'Active Links',
  staticDirectory: 'Static Directory (`public/`)',
  serverClient: '`.server.js` / `.client.js / ...`',
  environmentVariables: 'Environment Variables',
  httpHeaders: 'HTTP Headers',
  i18n: 'Internationalization (i18n)',
  pathAliases: 'Paths Aliases',
  preloading: 'Preloading',
  apiRoutes: 'API Routes',
  staticHostsOverview: 'Overview',
  githubPages: 'GitHub Pages',
  netlify: 'Netlify',
  cloudflarePages: 'Cloudflare Pages',
  cloudflare: 'Cloudflare',
  vercel: 'Vercel',
  awsLambda: 'AWS Lambda',
  netlifyFunctions: 'Netlify Functions',
  edgeonePages: 'EdgeOne Pages',
  aws: 'AWS',
  docker: 'Docker',
  selfHostedOther: 'Other',
  otherDeployment: 'Other deployment',
  authentication: 'Authentication',
  serverIntegration: 'Server integration',
  errorTracking: 'Error Tracking',
  cssInJs: 'CSS-in-JS',
  markdown: 'Markdown',
  store: 'Store (State Management)',
  graphql: 'GraphQL',
  vanillaUiTools: 'Vanilla UI tools',
  analytics: 'Analytics',
  componentLibraries: 'Component libraries',
  dataFetchingIntegration: 'Data fetching',
  serviceWorker: 'Service worker',
  viewTransitions: 'View transitions',
  uiFramework: 'UI framework',
  seeAlso: 'See also',
} as const
export type HeadingKey = keyof typeof Heading

const headingLinks: Record<HeadingKey, string> = {
  scaffoldNewVikeApp: '/new',
  addSsrSsgToVite: '/add',
  whyVike: '/why',
  faq: '/faq',
  openSourcePricing: '/pricing',
  freeProgram: '/free',
  extensions: '/extensions',
  team: '/team',
  dataFetching: '/data-fetching',
  preRendering: '/pre-rendering',
  ssrVsSpa: '/SSR-vs-SPA',
  headTags: '/head-tags',
  commonIssues: '/common-issues',
  routing: '/routing',
  baseUrl: '/base-url',
  activeLinks: '/active-links',
  staticDirectory: '/static-directory',
  serverClient: '/file-env',
  environmentVariables: '/env',
  httpHeaders: '/headers',
  i18n: '/i18n',
  pathAliases: '/path-aliases',
  preloading: '/preloading',
  apiRoutes: '/api-routes',
  staticHostsOverview: '/static-hosts',
  githubPages: '/github-pages',
  netlify: '/netlify',
  cloudflarePages: '/cloudflare-pages',
  cloudflare: '/cloudflare',
  vercel: '/vercel',
  awsLambda: '/aws-lambda',
  netlifyFunctions: '/netlify-functions',
  edgeonePages: '/edgeone-pages',
  aws: '/aws',
  docker: '/docker',
  selfHostedOther: '/deploy',
  otherDeployment: '/deploy',
  authentication: '/auth',
  serverIntegration: '/server-integration',
  errorTracking: '/error-tracking',
  cssInJs: '/css-in-js',
  markdown: '/markdown',
  store: '/store',
  graphql: '/graphql',
  vanillaUiTools: '/integration',
  analytics: '/integration',
  componentLibraries: '/integration',
  dataFetchingIntegration: '/integration',
  serviceWorker: '/integration',
  viewTransitions: '/integration',
  uiFramework: '/ui-frameworks',
  seeAlso: '/integration',
}

// get title and link for a heading key
export const getHeadingData = (headingKey: HeadingKey) => {
  return {
    title: Heading[headingKey],
    href: headingLinks[headingKey],
  }
}
